version: '3.8'
services:
  web:
    image: php:apache
    volumes:
     - "./:/var/www/html"
    ports:
     - 80:80
     - 443:443
  db:
   image: mysql:latest
   ports:
    - 3306:3306
   volumes:
    - "./db:/docker-entrypoint-initdb.d"
   environment: 
    - MYSQL_DATABASE=mydb  
    - MYSQL_USER=myuser
    - MYSQL_PASSWORD=mypassword
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - 8080:80
   environment:
    - PMA_HOST=db
    - PMA_PORT=3306